# This is the BeamMP-Server config file.
# Help & Documentation: `https://wiki.beammp.com/en/home/server-maintenance`
# IMPORTANT: Fill in the AuthKey with the key you got from `https://beammp.com/k/dashboard` on the left under "Keys"


[HTTP]
# Enables the internal HTTP server
HTTPServerEnabled = false
SSLKeyPath = "./.ssl/HttpServer/key.pem"
# Recommended to keep enabled. With SSL the server will serve https and requires valid key and cert files
UseSSL = true
SSLCertPath = "./.ssl/HttpServer/cert.pem"
HTTPServerPort = 8080

[General]
# If SendErrors is `true`, the server will send helpful info about crashes and other issues back to the BeamMP developers. This info may include your config, who is on your server at the time of the error, and similar general information. This kind of data is vital in helping us diagnose and fix issues faster. This has no impact on server performance. You can opt-out of this system by setting this to `false`
SendErrorsShowMessage = true
Name = "Babyback Ribs"
Port = 30814
ResourceFolder = "Resources"
# AuthKey has to be filled out in order to run the server
AuthKey = "905775d1-8282-4da7-b5f7-edf55dc12961"
Private = true
MaxPlayers = 10
Debug = false
Description = "BeamMP Default Description"
MaxCars = 10
Map = "/levels/gridmap_v2/info.json"
# You can turn on/off the SendErrors message you get on startup here
SendErrors = true

